package com.gentech.DefaultConstuctor;
class Employee{
    String EmpName;
    int empId;
    int sallary;
    int deptNo;
    int Age;
}
class Department {
    int deptNo;
    String name;
    String loc;
    String mang_name;
    int deptEmployeeNo;
}
class Insurance {
    int employee_id;
    String insurance_provider;
    int policy_number;
    String start_date;
    String end_date;
}
public class EmployeeDemo{
    public static void main(String[] args) {
        Employee Emp = new Employee();
        Emp.EmpName = "Asha";
        Emp.Age = 21;
        Emp.empId = 1;
        Emp.sallary = 20000;
        Emp.deptNo = 11;
        System.out.println("EmployeeName:" + Emp.EmpName);
        System.out.println("EmployeeAge:" + Emp.Age);
        System.out.println("EmployeeId:" + Emp.empId);
        System.out.println("EmployeeSallary:" + Emp.sallary);
        System.out.println("EmployeeDept:" + Emp.deptNo);
        Employee Emp1 = new Employee();
        Emp1.EmpName = "Aishu";
        Emp1.Age = 22;
        Emp1.empId = 2;
        Emp1.sallary = 25000;
        Emp1.deptNo = 12;
        System.out.println("EmployeeName:" + Emp1.EmpName);
        System.out.println("EmployeeAge:" + Emp1.Age);
        System.out.println("EmployeeId:" + Emp1.empId);
        System.out.println("EmployeeSallary:" + Emp1.sallary);
        System.out.println("EmployeeDept:" + Emp1.deptNo);
        Employee Emp2 = new Employee();
        Emp2.EmpName = "vijju";
        Emp2.Age = 23;
        Emp2.empId = 3;
        Emp2.sallary = 30000;
        Emp2.deptNo = 13;
        System.out.println("EmployeeName:" + Emp2.EmpName);
        System.out.println("EmployeeAge:" + Emp2.Age);
        System.out.println("EmployeeId:" + Emp2.empId);
        System.out.println("EmployeeSallary:" + Emp2.sallary);
        System.out.println("EmployeeDept:" + Emp2.deptNo);
        Employee Emp3 = new Employee();
        Emp3.EmpName = "Umra";
        Emp3.Age = 24;
        Emp3.empId = 4;
        Emp3.sallary = 35000;
        Emp3.deptNo = 14;
        System.out.println("EmployeeName:" + Emp3.EmpName);
        System.out.println("EmployeeAge:" + Emp3.Age);
        System.out.println("EmployeeId:" + Emp3.empId);
        System.out.println("EmployeeSallary:" + Emp3.sallary);
        System.out.println("EmployeeDept:" + Emp3.deptNo);
        Employee Emp4 = new Employee();
        Emp4.EmpName = "Sana";
        Emp4.Age = 25;
        Emp4.empId = 5;
        Emp4.sallary = 50000;
        Emp4.deptNo = 15;
        System.out.println("EmployeeName:" + Emp4.EmpName);
        System.out.println("EmployeeAge:" + Emp4.Age);
        System.out.println("EmployeeId:" + Emp4.empId);
        System.out.println("EmployeeSallary:" + Emp4.sallary);
        System.out.println("EmployeeDept:" + Emp4.deptNo);
        System.out.println("++++++++++++++++++++++++++++++++++++++++++");
        Department D1 = new Department();
        D1.deptEmployeeNo = 11;
        D1.loc = "Vijaynagar";
        D1.deptNo = 1;
        D1.name = "resarch";
        D1.mang_name = "k.s.krishna";
        System.out.println("DeptEmployeeNo:" + D1.deptEmployeeNo);
        System.out.println("Deptlocation:" + D1.loc);
        System.out.println("Deptname:" + D1.name);
        System.out.println("DeptManeger:" + D1.mang_name);
        System.out.println("DeptNumber:" + D1.deptNo);
        Department D2 = new Department();
        D2.deptEmployeeNo = 13;
        D2.loc = "VijaynagarMetro";
        D2.deptNo = 2;
        D2.name = "sales";
        D2.mang_name = "r.j ram";
        System.out.println("DeptEmployeeNo:" + D2.deptEmployeeNo);
        System.out.println("Deptlocation:" + D2.loc);
        System.out.println("Deptname:" + D2.name);
        System.out.println("DeptManeger:" + D2.mang_name);
        System.out.println("DeptNumber:" + D2.deptNo);
        Department D3 = new Department();
        D3.deptEmployeeNo = 13;
        D3.loc = "jayanagar";
        D3.deptNo = 3;
        D3.name = "parcharge";
        D3.mang_name = "s.v rao";
        System.out.println("DeptEmployeeNo:" + D3.deptEmployeeNo);
        System.out.println("Deptlocation:" + D3.loc);
        System.out.println("Deptname:" + D3.name);
        System.out.println("DeptManeger:" + D3.mang_name);
        System.out.println("DeptNumber:" + D3.deptNo);
        Department D4 = new Department();
        D4.deptEmployeeNo = 14;
        D4.loc = "Vijaynagarnear";
        D4.deptNo = 4;
        D4.name = "Accountent";
        D4.mang_name = "a.s ammu";
        System.out.println("DeptEmployeeNo:" + D4.deptEmployeeNo);
        System.out.println("Deptlocation:" + D4.loc);
        System.out.println("Deptname:" + D4.name);
        System.out.println("DeptManeger:" + D4.mang_name);
        System.out.println("DeptNumber:" + D4.deptNo);
        Department D5 = new Department();
        D5.deptEmployeeNo = 15;
        D5.loc = "Vijaynagar";
        D5.deptNo = 15;
        D5.name = "Goods store";
        D5.mang_name = "s.v sonu";
        System.out.println("DeptEmployeeNo:" + D5.deptEmployeeNo);
        System.out.println("Deptlocation:" + D5.loc);
        System.out.println("Deptname:" + D5.name);
        System.out.println("DeptManeger:" + D5.mang_name);
        System.out.println("DeptNumber:" + D5.deptNo);
        System.out.println("+++++++++++++++++++++++++++++++++++++++");
        Insurance I1 = new Insurance();
        I1.employee_id = 3;
        I1.insurance_provider = "Agents";
        I1.policy_number = 12345;
        I1.start_date ="12/03/2020";
        I1.end_date = "6/01/2024";
        System.out.println("Employee_id:" + I1.employee_id);
        System.out.println("Insurance_provider:" + I1.insurance_provider);
        System.out.println("policy_number:" + I1.policy_number);
        System.out.println("Start_date:" + I1.start_date);
        System.out.println("End_date:" + I1.end_date);
        Insurance I2 = new Insurance();
        I2.employee_id = 4;
        I2.insurance_provider = "Employee";
        I2.policy_number = 23456;
        I2.start_date = "12/09/2019";
        I2.end_date = "21/08/2004";
        System.out.println("Employee_id:" + I2.employee_id);
        System.out.println("Insurance_provider:" + I2.insurance_provider);
        System.out.println("policy_number:" + I2.policy_number);
        System.out.println("Start_date:" + I2.start_date);
        System.out.println("End_date:" + I2.end_date);
        Insurance I3 = new Insurance();
        I3.employee_id = 2;
        I3.insurance_provider = "Marketers";
        I3.policy_number = 34567;
        I3.start_date = "18/09/2008";
        I3.end_date = "31/03/2003";
        System.out.println("Employee_id:" + I3.employee_id);
        System.out.println("Insurance_provider:" + I3.insurance_provider);
        System.out.println("policy_number:" + I3.policy_number);
        System.out.println("Start_date:" + I3.start_date);
        System.out.println("End_date:" + I3.end_date);
        Insurance I4 = new Insurance();
        I4.employee_id = 5;
        I4.insurance_provider = "sales";
        I4.policy_number = 78965;
        I4.start_date = "8/4/2019";
        I4.end_date = "5/6/2005";
        System.out.println("Employee_id:" + I4.employee_id);
        System.out.println("Insurance_provider:" + I4.insurance_provider);
        System.out.println("policy_number:" + I4.policy_number);
        System.out.println("Start_date:" + I4.start_date);
        System.out.println("End_date:" + I4.end_date);
        Insurance I5 = new Insurance();
        I5.employee_id = 8;
        I5.insurance_provider = "Customizer";
        I5.policy_number = 445678;
        I5.start_date = "9/6/2001";
        I5.end_date = "3/9/2000";
        System.out.println("Employee_id:" + I5.employee_id);
        System.out.println("Insurance_provider:" + I5.insurance_provider);
        System.out.println("policy_number:" + I5.policy_number);
        System.out.println("Start_date:" + I5.start_date);
        System.out.println("End_date:" + I5.end_date);
    }
}



