package com.gentech.DefaultConstuctor;
class Products{
    int ProductID;
    String Category;
    int UnitPrice;
    int StockQuantity;
}
class  Order{
    int OrderID;
    int CustomerID;
    String OrderDate;
    int TotalAmount;
    String OrderStatus;
}
class Shipping{
    int  ShippingID;
    int  OrderID;
    String ShippingDate;
    String ShippingMethod;
}
public class ProductDemo {
    public static void main(String[] args) {
        Products p1 = new Products();
        p1.ProductID=1;
        p1.Category="good";
        p1.UnitPrice=10;
        p1.StockQuantity=5;
        System.out.println("ProductID:"+p1.ProductID);
        System.out.println("category:"+p1.Category);
        System.out.println("UnitPrice:"+p1.UnitPrice);
        System.out.println("StockQuantity:"+p1.StockQuantity);
        Products p2 = new Products();
        p2.ProductID=2;
        p2.Category="very good";
        p2.UnitPrice=10;
        p2.StockQuantity=5;
        System.out.println("ProductID:"+ p2.ProductID);
        System.out.println("category:"+ p2.Category);
        System.out.println("UnitPrice:"+ p2.UnitPrice);
        System.out.println("StockQuantity:"+ p2.StockQuantity);
        Products p3 = new Products();
        p3.ProductID=3;
        p3.Category="good";
        p3.UnitPrice=20;
        p3.StockQuantity=5;
        System.out.println("ProductID:"+ p3.ProductID);
        System.out.println("category:"+ p3.Category);
        System.out.println("UnitPrice:"+ p3.UnitPrice);
        System.out.println("StockQuantity:"+ p3.StockQuantity);
        Products p4 = new Products();
        p4.ProductID=4;
        p4.Category="ok-ok";
        p4.UnitPrice=40;
        p4.StockQuantity=5;
        System.out.println("ProductID:"+ p4.ProductID);
        System.out.println("category:"+ p4.Category);
        System.out.println("UnitPrice:"+ p4.UnitPrice);
        System.out.println("StockQuantity:"+ p4.StockQuantity);
        Products p5 = new Products();
        p5.ProductID=5;
        p5.Category="good";
        p5.UnitPrice=50;
        p5.StockQuantity=9;
        System.out.println("ProductID:"+ p5.ProductID);
        System.out.println("category:"+ p5.Category);
        System.out.println("UnitPrice:"+ p5.UnitPrice);
        System.out.println("StockQuantity:"+ p5.StockQuantity);
        System.out.println("++++++++++++++++++++++++++++++++++++++++");
        Order o1=new Order();
        o1.CustomerID=12;
        o1.OrderDate="12/9/24";
        o1.OrderID=11;
        o1.TotalAmount=3564;
        o1.OrderStatus="paid";
        System.out.println("CustomerID:"+o1.CustomerID);
        System.out.println("OrderID:"+o1.OrderID);
        System.out.println("OrderDate:"+o1.OrderDate);
        System.out.println("TotalAmount:"+o1.TotalAmount);
        System.out.println("OrderStatus:"+o1.OrderStatus);
        Order o2 =new Order();
        o2.CustomerID=18;
        o2.OrderDate="19/9/2004";
        o2.OrderID=41;
        o2.TotalAmount=9864;
        o2.OrderStatus="paid";
        System.out.println("CustomerID:"+ o2.CustomerID);
        System.out.println("OrderID:"+ o2.OrderID);
        System.out.println("OrderDate:"+ o2.OrderDate);
        System.out.println("TotalAmount:"+ o2.TotalAmount);
        System.out.println("OrderStatus:"+ o2.OrderStatus);
        Order o3 =new Order();
        o3.CustomerID=23;
        o3.OrderDate="25/9/24";
        o3.OrderID=71;
        o3.TotalAmount=7764;
        o3.OrderStatus="paid";
        System.out.println("CustomerID:"+ o3.CustomerID);
        System.out.println("OrderID:"+ o3.OrderID);
        System.out.println("OrderDate:"+ o3.OrderDate);
        System.out.println("TotalAmount:"+ o3.TotalAmount);
        System.out.println("OrderStatus:"+ o3.OrderStatus);
        Order o4 =new Order();
        o4.CustomerID=62;
        o4.OrderDate="31/9/24";
        o4.OrderID=10;
        o4.TotalAmount=3004;
        o4.OrderStatus="paid";
        System.out.println("CustomerID:"+o4.CustomerID);
        System.out.println("OrderID:"+o4.OrderID);
        System.out.println("OrderDate:"+o4.OrderDate);
        System.out.println("TotalAmount:"+o4.TotalAmount);
        System.out.println("OrderStatus:"+o4.OrderStatus);
        Order o5 =new Order();
        o5.CustomerID=12;
        o5.OrderDate="12/9/24";
        o5.OrderID=11;
        o5.TotalAmount=3564;
        o5.OrderStatus="paid";
        System.out.println("CustomerID:"+ o5.CustomerID);
        System.out.println("OrderID:"+ o5.OrderID);
        System.out.println("OrderDate:"+ o5.OrderDate);
        System.out.println("TotalAmount:"+ o5.TotalAmount);
        System.out.println("OrderStatus:"+ o5.OrderStatus);
        System.out.println("++++++++++++++++++++++++++++++++++++++++++++");
        Shipping s1=new Shipping();
        s1.OrderID=11;
        s1.ShippingDate="23/05/2002";
        s1.ShippingMethod="Air";
        s1.ShippingID=98;
        System.out.println("OrderId:"+s1.OrderID);
        System.out.println("ShippingID:"+s1.ShippingID);
        System.out.println("ShippingDate:"+s1.ShippingDate);
        System.out.println("ShippingMethode:"+s1.ShippingMethod);
        Shipping s2 =new Shipping();
        s2.OrderID=21;
        s2.ShippingDate="23/06/2002";
        s2.ShippingMethod="Air";
        s2.ShippingID=67;
        System.out.println("OrderId:"+ s2.OrderID);
        System.out.println("ShippingID:"+ s2.ShippingID);
        System.out.println("ShippingDate:"+ s2.ShippingDate);
        System.out.println("ShippingMethode:"+ s2.ShippingMethod);
        Shipping s3 =new Shipping();
        s3.OrderID=41;
        s3.ShippingDate="25/05/2012";
        s3.ShippingMethod="Air";
        s3.ShippingID=77;
        System.out.println("OrderId:"+ s3.OrderID);
        System.out.println("ShippingID:"+ s3.ShippingID);
        System.out.println("ShippingDate:"+ s3.ShippingDate);
        System.out.println("ShippingMethode:"+ s3.ShippingMethod);
        Shipping s4 =new Shipping();
        s4.OrderID=21;
        s4.ShippingDate="23/09/2019";
        s4.ShippingMethod="Air";
        s4.ShippingID=96;
        System.out.println("OrderId:"+ s4.OrderID);
        System.out.println("ShippingID:"+ s4.ShippingID);
        System.out.println("ShippingDate:"+ s4.ShippingDate);
        System.out.println("ShippingMethode:"+ s4.ShippingMethod);
        Shipping s5 =new Shipping();
        s5.OrderID=34;
        s5.ShippingDate="27/09/2002";
        s5.ShippingMethod="Air";
        s5.ShippingID=73;
        System.out.println("OrderId:"+ s5.OrderID);
        System.out.println("ShippingID:"+ s5.ShippingID);
        System.out.println("ShippingDate:"+ s5.ShippingDate);
        System.out.println("ShippingMethode:"+ s5.ShippingMethod);
        System.out.println("+++++++++++++++++++++++++++++++++++++++++");
    }
}


