package com.gentech.DefaultConstuctor;
class Purchase{
    String PName;
    String PurchaseDate;
    int ProductID ;
    int Quantity ;
    int UnitPrice;
    int TotalAmount;
    String PaymentStatus ;
}
class Sales{
    String salesName;
    String SalesDate;
    int ProductID ;
    int Quantity ;
    int UnitPrice;
    int TotalAmount;
    String PaymentStatus ;
}
class Inventory{
    int ProductID;
    String ProductName;
    int QuantityInStock;
    int ReorderLevel;
    int UnitPrice;
}
public class PurchaseDemo{
    public static void main(String[] args) {
        Purchase p1=new Purchase();
        p1.PName="notebooks";
        p1.PurchaseDate="12/02/2002";
        p1.ProductID=11 ;
        p1.Quantity=10 ;
        p1.UnitPrice=20;
        p1.TotalAmount=200;
        p1.PaymentStatus="cash";
        System.out.println("PurchaseDate:"+p1.PurchaseDate);
        System.out.println("Purchaseproductname:"+p1.PName);
        System.out.println("ProductId:"+p1.ProductID);
        System.out.println("Quantity:"+p1.Quantity);
        System.out.println("UnitPrice:"+p1.UnitPrice);
        System.out.println("TotalPrice:"+p1.TotalAmount);
        System.out.println("PaymentStatus:"+p1.PaymentStatus);
        Purchase p2 =new Purchase();
        p2.PName="Earphone";
        p2.PurchaseDate="16/02/2002";
        p2.ProductID=11 ;
        p2.Quantity=9;
        p2.UnitPrice=80;
        p2.TotalAmount=640;
        p2.PaymentStatus="cash";
        System.out.println("Pruductsname:"+ p2.PName);
        System.out.println("PurchaseDate:"+ p2.PurchaseDate);
        System.out.println("ProductId:"+ p2.ProductID);
        System.out.println("Quantity:"+ p2.Quantity);
        System.out.println("UnitPrice:"+ p2.UnitPrice);
        System.out.println("TotalPrice:"+ p2.TotalAmount);
        System.out.println("PaymentStatus:"+ p2.PaymentStatus);
        Purchase p3 =new Purchase();
        p3.PName="phone";
        p3.PurchaseDate="16/07/2002";
        p3.ProductID=15 ;
        p3.Quantity=8;
        p3.UnitPrice=8000;
        p3.TotalAmount=60040;
        p3.PaymentStatus="cash";
        System.out.println("Pruductsname:"+ p3.PName);
        System.out.println("PurchaseDate:"+ p3.PurchaseDate);
        System.out.println("ProductId:"+ p3.ProductID);
        System.out.println("Quantity:"+ p3.Quantity);
        System.out.println("UnitPrice:"+ p3.UnitPrice);
        System.out.println("TotalPrice:"+ p3.TotalAmount);
        System.out.println("PaymentStatus:"+ p3.PaymentStatus);
        Purchase p4 =new Purchase();
        p4.PName="laptop";
        p4.PurchaseDate="16/12/2002";
        p4.ProductID=44 ;
        p4.Quantity=7;
        p4.UnitPrice=70;
        p4.TotalAmount=777640;
        p4.PaymentStatus="Phonepay";
        System.out.println("Pruductsname:"+ p4.PName);
        System.out.println("PurchaseDate:"+ p4.PurchaseDate);
        System.out.println("ProductId:"+ p4.ProductID);
        System.out.println("Quantity:"+ p4.Quantity);
        System.out.println("UnitPrice:"+ p4.UnitPrice);
        System.out.println("TotalPrice:"+ p4.TotalAmount);
        System.out.println("PaymentStatus:"+ p4.PaymentStatus);
        Purchase p5 =new Purchase();
        p5.PName="Mobile";
        p5.PurchaseDate="16/02/2003";
        p5.ProductID=16 ;
        p5.Quantity=13;
        p5.UnitPrice=80900;
        p5.TotalAmount=6000040;
        p5.PaymentStatus="phonepay";
        System.out.println("Pruductsname:"+ p5.PName);
        System.out.println("PurchaseDate:"+ p5.PurchaseDate);
        System.out.println("ProductId:"+ p5.ProductID);
        System.out.println("Quantity:"+ p5.Quantity);
        System.out.println("UnitPrice:"+ p5.UnitPrice);
        System.out.println("TotalPrice:"+ p5.TotalAmount);
        System.out.println("PaymentStatus:"+ p5.PaymentStatus);
        System.out.println("++++++++++++++++++++++++++++++++++++++++++++++++++");
        Sales s1=new Sales();
        s1.salesName="notebooks";
        s1.SalesDate="12/03/2002";
        s1.ProductID=1 ;
        s1.Quantity=10 ;
        s1.UnitPrice=20;
        s1.TotalAmount=200;
        s1. PaymentStatus="cash";
        System.out.println("ProductName:"+s1.salesName);
        System.out.println("SalesDate:"+s1.SalesDate);
        System.out.println("ProductId:"+ s1.ProductID);
        System.out.println("Quantity:"+ s1.Quantity);
        System.out.println("UnitPrice:"+ s1.UnitPrice);
        System.out.println("TotalPrice:"+ s1.TotalAmount);
        System.out.println("PaymentStatus:"+s1.PaymentStatus);
        Sales s2 =new Sales();
        s2.salesName="Phones";
        s2.SalesDate="12/04/2002";
        s2.ProductID=12;
        s2.Quantity=16 ;
        s2.UnitPrice=20000;
        s2.TotalAmount=2789700;
        s2. PaymentStatus="phonepay";
        System.out.println("ProductName:"+ s2.salesName);
        System.out.println("SalesDate:"+ s2.SalesDate);
        System.out.println("ProductId:"+ p4.ProductID);
        System.out.println("Quantity:"+ s2.Quantity);
        System.out.println("UnitPrice:"+ s2.UnitPrice);
        System.out.println("TotalPrice:"+ s2.TotalAmount);
        System.out.println("PaymentStatus:"+ s2.PaymentStatus);
        Sales s3 =new Sales();
        s3.salesName="EarPhones";
        s3.SalesDate="24/04/2002";
        s3.ProductID=12;
        s3.Quantity=16 ;
        s3.UnitPrice=2800;
        s3.TotalAmount=21023300;
        s3. PaymentStatus="phonepay";
        System.out.println("ProductName:"+ s3.salesName);
        System.out.println("SalesDate:"+ s3.SalesDate);
        System.out.println("ProductId:"+ p4.ProductID);
        System.out.println("Quantity:"+ s3.Quantity);
        System.out.println("UnitPrice:"+ s3.UnitPrice);
        System.out.println("TotalPrice:"+ s3.TotalAmount);
        System.out.println("PaymentStatus:"+ s3.PaymentStatus);
        Sales s4 =new Sales();
        s4.salesName="iphone";
        s4.SalesDate="17/04/2019";
        s4.ProductID=24;
        s4.Quantity=11 ;
        s4.UnitPrice=2560;
        s4.TotalAmount=1089700;
        s4. PaymentStatus="phonepay";
        System.out.println("ProductName:"+ s4.salesName);
        System.out.println("SalesDate:"+ s4.SalesDate);
        System.out.println("ProductId:"+ p4.ProductID);
        System.out.println("Quantity:"+ s4.Quantity);
        System.out.println("UnitPrice:"+ s4.UnitPrice);
        System.out.println("TotalPrice:"+ s4.TotalAmount);
        System.out.println("PaymentStatus:"+ s4.PaymentStatus);
        Sales s5 =new Sales();
        s5.salesName="Tab";
        s5.SalesDate="18/04/2002";
        s5.ProductID=13;
        s5.Quantity=10 ;
        s5.UnitPrice=2000;
        s5.TotalAmount=2000000;
        s5. PaymentStatus="phonepay";
        System.out.println("ProductName:"+ s5.salesName);
        System.out.println("SalesDate:"+ s5.SalesDate);
        System.out.println("ProductId:"+ p4.ProductID);
        System.out.println("Quantity:"+ s5.Quantity);
        System.out.println("UnitPrice:"+ s5.UnitPrice);
        System.out.println("TotalPrice:"+ s5.TotalAmount);
        System.out.println("PaymentStatus:"+ s5.PaymentStatus);
        System.out.println("++++++++++++++++++++++++++++++++++++++++++++");
        Inventory I1=new Inventory();
        I1. ProductID=12;
        I1. ProductName="notebooks";
        I1.QuantityInStock=19;
        I1.ReorderLevel=20;
        I1.UnitPrice=150;
        System.out.println("ProductId:"+I1.ProductID);
        System.out.println("ProductName:"+I1.ProductName);
        System.out.println("QuantityInStoke:"+I1.QuantityInStock);
        System.out.println("ReorderLevel:"+I1.ReorderLevel);
        System.out.println("UnitPrice:"+I1.UnitPrice);
        Inventory I2 =new Inventory();
        I2. ProductID=12;
        I2. ProductName="books";
        I2.QuantityInStock=14;
        I2.ReorderLevel=80;
        I2.UnitPrice=10;
        System.out.println("ProductId:"+ I2.ProductID);
        System.out.println("ProductName:"+ I2.ProductName);
        System.out.println("QuantityInStoke:"+ I2.QuantityInStock);
        System.out.println("ReorderLevel:"+ I2.ReorderLevel);
        System.out.println("UnitPrice:"+ I2.UnitPrice);
        Inventory I3 =new Inventory();
        I3. ProductID=19;
        I3. ProductName="phones";
        I3.QuantityInStock=19;
        I3.ReorderLevel=23;
        I3.UnitPrice=11;
        System.out.println("ProductId:"+ I3.ProductID);
        System.out.println("ProductName:"+ I3.ProductName);
        System.out.println("QuantityInStoke:"+ I3.QuantityInStock);
        System.out.println("ReorderLevel:"+ I3.ReorderLevel);
        System.out.println("UnitPrice:"+ I3.UnitPrice);
        Inventory I4 =new Inventory();
        I4. ProductID=18;
        I4. ProductName="Tabs";
        I4.QuantityInStock=55;
        I4.ReorderLevel=10;
        I4.UnitPrice=15000;
        System.out.println("ProductId:"+ I4.ProductID);
        System.out.println("ProductName:"+ I4.ProductName);
        System.out.println("QuantityInStoke:"+ I4.QuantityInStock);
        System.out.println("ReorderLevel:"+ I4.ReorderLevel);
        System.out.println("UnitPrice:"+ I4.UnitPrice);
        Inventory I5 =new Inventory();
        I5. ProductID=77;
        I5. ProductName="ipad";
        I5.QuantityInStock=67;
        I5.ReorderLevel=27;
        I5.UnitPrice=17000;
        System.out.println("ProductId:"+ I5.ProductID);
        System.out.println("ProductName:"+ I5.ProductName);
        System.out.println("QuantityInStoke:"+ I5.QuantityInStock);
        System.out.println("ReorderLevel:"+ I5.ReorderLevel);
        System.out.println("UnitPrice:"+ I5.UnitPrice);


    }
}


